import type { Project } from "./types.ts";

export const projects_db : Project[] = [
	{
			"url": "https://nimaniazi.com",
			"image": "https://nimaniazi.com/static/avatar.jpg",
			"name": "Nima",
			"description_1": "Hi! My name is Nima. I'm a developer and software engineer based in Brooklyn, NY. This is my portfolio website showcasing the projects I've been working on. To learn more about me checkout my personal website nimaniazi.com",
			"description_2":"",
	},
  {
    "url": "https://neckboard.com",
    "image": "https://nimaniazi.com/static/neckboard.png",
    "name": "Neckboard",
		"description_1": "Neckboard is my biggest project yet. With over 3000 monthly users, it's an educational web application built using VueJS that helps musicians all across the world make sense of the fretboard of their instruments.",
			"description_2":"Designed by a musician for musicians. You can customize the virtual fretboard to fit your custom needs.",
  },
  {
    "url": "https://nimaniazi.com/nardin",
    "image": "https://nimaniazi.com/static/nardin/thumbnail.jpg",
    "name": "Nardin",
		"description_1": "Nardin is a hardware audio instrument and multi-effect unit. It consists of a polyphonic synth with a sequencer and a bunch of audio effects. What makes it unique is the ability to automate various parameters using the touchstrip it has to morph between different sonic states.",
			"description_2":"To learn more you can check out this link.",
  },
  {
    "url": "https://github.com/nimanns/delay",
    "image": "https://nimaniazi.com/static/dualdelay.png",
    "name": "Dual Delay VST3 Plugin",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://github.com/nimanns/piclure",
    "image": "https://nimaniazi.com/static/piclure.png",
    "name": "Piclure - A Photoblog",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://github.com/nimanns/medds",
    "image": "https://nimaniazi.com/static/medds.png",
    "name": "medds - Medication Reminder Android App",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/loopcrafthub",
    "image": "https://nimaniazi.com/static/loopcrafthub/thumbnail.jpg",
    "name": "LoopCraftHub - AI Music Generator",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/citizenjane",
    "image": "https://nimaniazi.com/static/citizenjane/thumbnail.jpg",
    "name": "Citizen Jane",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/nila",
    "image": "https://nimaniazi.com/static/nila/thumbnail.jpg",
    "name": "Nila - Smart Alarm Sleeping Mask",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/veggiesandmeat",
    "image": "https://nimaniazi.com/static/veggiesandmeat/thumbnail.jpg",
    "name": "Veggies & Meat - Arcade Game",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/binaryphonestand",
    "image": "https://nimaniazi.com/static/binaryphonestand/thumbnail.jpg",
    "name": "Binary Phone Stand",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimanns.github.io/juvenile-demo/",
    "image": "https://nimaniazi.com/static/juvenile.png",
    "name": "juvenile - p5.js audio visualizer",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/itp/energy/7/",
    "image": "https://nimaniazi.com/static/kineticwah.png",
    "name": "The Kinetic Wah Pedal",
		"description_1": "test",
			"description_2":"",
  },
  {
    "url": "https://nimaniazi.com/itp/light/9",
    "image": "https://nimaniazi.com/static/circle.png",
    "name": "Circle - An interactive task light",
		"description_1": "test",
			"description_2":"",
  }
]
